### ISSUE TITLE
Cant't force the version of node.js to 5.1 in Ubuntu 14.04

### ISSUE THREAD

**Issue by michaelkarrer81** [saltstack-formulas/node-formula#22]
Sorry if this is not a real "Issue/Bug" but most likely a misunderstanding by me:

I would like to install node.js and npm in a specific version e.g. 5.1 on an Ubuntu 14.04 Server:

### What i did:
I added your github repository to ```gitfs_remotes``` in the salt-master etc config file and applied a pillar file with
```
node:
  version: 5.1.0
  checksum: 25b2d3b7dd57fe47a483539fea240a3c6bbbdab4d89a45a812134cf1380ecb94
```
to the virtual box machine ```minion1``` 

If i run ```salt minion1 pillar.items``` everything looks alright and the pillar data was correctly received by minion1.

I then apply a state to ```minion1``` with
```
include:
  - node 

npm packages:
  npm.installed:
    - pkgs:
      - less
      - less-plugin-clean-css
      - push-to-deploy
    - require:
      - pkg: nodejs
```
This will install the package ```node```(js) and ```npm``` but will **not install the desired version**?! 
I also tried with
```
...
    - require:
      - pkg: node

```
instead of package nodejs but this throws error?!

### The Problem
If i run ```nodejs --version``` on minion1 i get ```v0.12.9``` but i expected Version **5.1** as defined in the pillar?

### What i want to do:
- Force in a state file that a specific version (5.1) of node.js is/gets installed on Ubuntu 14.04. 
- Would be even nicer if i could specify the version of node.js without a pillar file

Any help would be very much appreciated.
