### ISSUE TITLE
Data passed to highstate outputter is not a valid highstate return.

### ISSUE THREAD

**Issue by NiteshSaxena** [saltstack-formulas/node-formula#33]
I am trying to install node-v4.5.0 using formula, I am getting this error. Can anyone help me how to solve it.

When running the command below on master
`sudo salt 'envdev' state.apply`

I am getting following error:
```
Data passed to highstate outputter is not a valid highstate return: {'envdev': ['Pillar failed to render with the following messages:', "Rendering SLS 'node' failed. Please see master log for details."]}
ERROR: Minions returned with non-zero exit code
```

Below is my /srv/salt/top.sls file:
```
base:
  'envdev':
    - node 
```

I have copied node directory from formula to /srv/salt/ directory.

Below is my /srv/pillar/top.sls file.
```
base:
  '*':
    - node
```

Below is my /srv/pillar/node.sls file.
```
# Install from source:
node:
  version: 4.5.0
  install_from_source: False
  checksum: 5678ad94ee35e40fc3a2c545e136a0dc946ac4c039fca5898e1ea51ecf9e7c39
  make_jobs: 2

# Install from binary:
node:
  version: 4.5.0
  install_from_binary: True
  checksum: 5678ad94ee35e40fc3a2c545e136a0dc946ac4c039fca5898e1ea51ecf9e7c39

# Install from PPA:
# node:
#  version: 4.5.0
#  install_from_ppa: False
#  ppa:
#    repository_url: https://deb.nodesource.com/setup_4.x
```
