### ISSUE TITLE
[FEATURE] Ability to set exact major version in pkg repository

### ISSUE THREAD

**Issue by MurzNN** [saltstack-formulas/node-formula#54]
### Is your feature request related to a problem?
I need to have the 10 version of node on Debian/Ubuntu systems, I fill this pillar:
```
node:
  version: 10
  pkg:
    version: 10
    use_upstream_repo: true
```
It installs successfully without warnings, but, as result, I have 12 version of node:
```
$ node -v
v12.20.1
```
and in the `/etc/apt/sources.list.d/nodesource.list` file there are:
```
deb https://deb.nodesource.com/node_12.x focal main
```

### Describe the solution you'd like
Will be good to have ability to force set needed node major version from pillar file.
